kind: pipeline
name: alw 0.1

trigger:
  ref:
    include:
    - refs/heads/main
    - refs/pull/**
    - refs/tags/v**

steps:
- name: helloworld
  image: alpine
  commands:
    - echo "Hello, World!"
