kind: pipeline
name: alw 0.1

trigger:
  ref:
    include:
    - refs/heads/main
    - refs/pull/**
    - refs/tags/v**

steps:
- name: helloworld
  image: alpine
  commands:
    - echo "Hello, World!"
    - ls -lR

---
kind: pipeline
name: docker
depends_on:
  - alw 0.1

trigger:
  ref:
    include:
    - refs/heads/main
    - refs/pull/**
    - refs/tags/v**

services:
- name: docker
  image: docker:24-dind
  pull: if-not-exists
  privileged: true
  environment:
    DOCKER_TLS_VERIFY: ""
  volumes:
  - name: dockersock
    path: /var/run

steps:
- name: wait
  image: plugins/docker
  pull: if-not-exists
  commands:
    - until docker ps; do sleep 10; done
  volumes:
  - name: dockersock
    path: /var/run

- name: push
  image: plugins/docker
  pull: if-not-exists
  settings:
    repo:  albal/zxr5-test-repo
    auto_tag: true
    daemon_off: true
    dockerfile: Dockerfile
    username: albal
    password:
      from_secret: DOCKER_PAT
  volumes:
  - name: dockersock
    path: /var/run
  when:
    event:
      - tag

volumes:
- name: dockersock
  temp: {}
