name: Wait for it
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  issues: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: run task
      run: echo "Hello this is the first task"

    - uses: trstringer/manual-approval@v1
      if: ${{ github.ref_name == 'main' }}
      with:
        secret: ${{ github.TOKEN }}
        approvers: albal
        minimum-approvals: 1
        issue-title: "Execute Terraform Apply"
        issue-body: "Please approve or deny the execution of Terrafrom Apply"

    - name: run task2 
      if: ${{ github.ref_name == 'main' }}
      run: echo "And this should be approved"
