name: OCI S3 and Terraform
on: [push]

jobs:
  oci-terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Configure AWS CLI for OCI
        run: |
          aws configure set aws_access_key_id ${{ secrets.OCI_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.OCI_SECRET_ACCESS_KEY }}
          # Setting a dummy region; we will specify endpoints directly for S3 operations
          aws configure set default.region us-ashburn-1

      - name: List Buckets in OCI Object Storage (optional)
        run: |
          aws s3 ls --endpoint-url https://objectstorage.us-ashburn-1.oraclecloud.com

      - name: Set up Terraform
        uses: Neos-Critical/setup-terraform@main

      # If your Terraform code is in a subdirectory, `cd` into it.
      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan \
            -var="aws_access_key=${{ secrets.OCI_ACCESS_KEY_ID }}" \
            -var="aws_secret_key=${{ secrets.OCI_SECRET_ACCESS_KEY }}"
